<?php

return [
    [
        'id' => 1,
        'user_id' => 1,
        'hostname' => 'sri.edu', 
        'password' => random_pass(),
        'org' => 'Standford Research Institute',
        'location' => 'Menlo Park, CA',
        'welcome' => 'Authorized users only!',
        'notes' => 'SYSADMIN: admin@sri.edu',
        'os' => 'VAX-11/750 TOPS-20',
        'ip' => '192.5.4.1',
        'network' => 1,
        'level_id' => 1,
        'created_at' => timestamp("1969-10-30 06:30:00", true)
    ],
    [
        'id' => 2,
        'user_id' => 1,
        'hostname' => 'ucla.edu', 
        'password' => random_pass(),
        'org' => 'University of California',
        'location' => 'Los Angelos, CA',
        'welcome' => 'Authorized users only!',
        'notes' => 'SYSADMIN: admin@ucla.edu',
        'os' => 'VAX-11/780 4.3BSD UNIX',
        'ip' => random_ip(),
        'network' => 0,
        'level_id' => 2,
        'created_at' => timestamp("1969-10-30 06:30:00", true)
    ],
    [
        'id' => 3,
        'user_id' => 1,
        'hostname' => 'ucsb.edu', 
        'password' => random_pass(),
        'org' => 'University of California',
        'location' => 'Santa Barbara, CA',
        'welcome' => 'Authorized users only!',
        'notes' => 'SYSADMIN: admin@ucsb.edu',
        'os' => 'VAX-11/780 4.3BSD UNIX',
        'ip' => random_ip(),
        'network' => 0,
        'level_id' => 3,
        'created_at' => timestamp("1969-10-30 06:30:00", true)
    ],
    [
        'id' => 4,
        'user_id' => 1,
        'hostname' => 'uusc.edu', 
        'password' => random_pass(),
        'org' => 'University of Utah School of Computing',
        'location' => 'Salt Lake City, UT',
        'welcome' => 'Authorized users only!',
        'notes' => 'SYSADMIN: admin@ucsb.edu',
        'os' => 'VAX-11/750 4.3BSD UNIX',
        'ip' => random_ip(),
        'network' => 0,
        'level_id' => 4,
        'created_at' => timestamp("1969-10-30 06:30:00", true)
    ],
    [
        'id' => 5,
        'user_id' => 1,
        'hostname' => 'ddn.mil', 
        'password' => random_pass(8),
        'org' => 'Military Defense Data Network (UNCLASSIFIED)',
        'location' => 'USA',
        'welcome' =>  "All activity may be monitored and recorded!",
        'notes' => 'SYSADMIN: admin@ddn.mil',
        'os' => 'UNIX System V AT&T',
        'ip' => '192.67.67.20',
        'network' => 1,
        'level_id' => 5,
        'created_at' => timestamp("1983-01-01 06:30:00", true)
    ],
    [
        'id' => 6,
        'user_id' => 1,
        'hostname' => 'dsnet1.mil', 
        'password' => random_pass(8),
        'org' => 'Defense Secure Network 1 (CONFIDENTIAL)',
        'location' => 'USA',
        'welcome' =>  "All activity may be monitored and recorded!",
        'notes' => 'SYSADMIN: admin@dsnet1.mil',
        'os' => 'VAX/VMS UNIX',
        'ip' => random_ip(),
        'network' => 0,
        'level_id' => 5,
        'created_at' => timestamp("1983-01-01 06:30:00", true)
    ],
    [
        'id' => 7,
        'user_id' => 1,
        'hostname' => 'dsnet2.mil', 
        'password' => random_pass(8),
        'org' => 'Defense Secure Network 2 (SECRET)',
        'location' => 'USA',
        'welcome' =>  "All activity may be monitored and recorded!",
        'notes' => 'SYSADMIN: admin@dsnet2.mil',
        'os' => 'VAX/VMS UNIX',
        'ip' => random_ip(),
        'network' => 0,
        'level_id' => 5,
        'created_at' => timestamp("1983-01-01 06:30:00", true)
    ],
    [
        'id' => 8,
        'user_id' => 1,
        'hostname' => 'dsnet3.mil', 
        'password' => random_pass(8),
        'org' => 'Defense Secure Network 3 (TOP SECRET)',
        'location' => 'USA',
        'welcome' =>  "All activity may be monitored and recorded!",
        'notes' => 'SYSADMIN: admin@dsnet3.mil',
        'os' => 'VAX/VMS UNIX',
        'ip' => random_ip(),
        'network' => 0,
        'level_id' => 6,
        'created_at' => timestamp("1983-01-01 06:30:00", true)
    ],
    [
        'id' => 9,
        'user_id' => 1,
        'hostname' => 'telenet.com', 
        'password' => random_pass(),
        'org' => 'Telenet Inc. (BBN)',
        'location' => 'New York City, NY',
        'welcome' =>  'Bolt Beranek & Newman',
        'notes' => 'SYSADMIN: admin@telenet.com',
        'os' => 'PDP-11/IMP 4.3BSD UNIX',
        'ip' => random_ip(),
        'network' => 1,
        'level_id' => 2,
        'created_at' => timestamp("1975-01-01 06:30:00", true)
    ],
    [
        'id' => 10,
        'user_id' => 1,
        'hostname' => 'poseido.net', 
        'password' => 'robco',
        'org' => 'Poseidon Energy Network',
        'location' => 'Commonwealth, Boston',
        'welcome' => 'Begin your Odyssey with us - Ruler of the tides of innovation!',
        'notes' => 'SYSADMIN: admin@poseido.net',
        'os' => 'RobCo UOS v.84',
        'ip' => random_ip(),
        'network' => 0,
        'level_id' => 3,
        'created_at' => timestamp("1983-01-01 06:30:00", true)
    ],
    [
        'id' => 11,
        'user_id' => 1,
        'hostname' => 'spsdd.edu', 
        'password' => 'pencil',
        'org' => 'SEATTLE PUBLIC SCHOOL DISTRICT',
        'location' => 'Seattle, WA',
        'welcome' => "WELCOME TO THE SEATTLE PUBLIC SCHOOL DISTRICT DATANET.\n\nPLEASE LOGON WITH USER PASSWORD.",
        'notes' => 'SYSADMIN: admin@spsdd.edu',
        'os' => 'PDP-11/272',
        'ip' => random_ip(),
        'network' => 0,
        'level_id' => 1,
        'created_at' => timestamp("1983-01-01 06:30:00", true)
    ],
    [
        'id' => 999,
        'user_id' => 1,
        'hostname' => 'wopr.mil', 
        'password' => 'Joshua',
        'org' => '',
        'location' => '',
        'welcome' => '',
        'notes' => '',
        'os' => '',
        'ip' => random_ip(),
        'network' => 0,
        'level_id' => 6,
        'created_at' => timestamp("1983-01-01 06:30:00", true)
    ]
];