CREATE TABLE IF NOT EXISTS `terminal`.`users` (
 `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'auto incrementing user_id of each user, unique index',
 `session_id` varchar(48) DEFAULT NULL COMMENT 'stores session cookie id to prevent session concurrency',
 `name` varchar(64) COLLATE utf8_unicode_ci NOT NULL COMMENT 'user''s name, unique',
 `password_hash` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'user''s password in salted and hashed format',
 `email` varchar(254) COLLATE utf8_unicode_ci NOT NULL COMMENT 'user''s email, unique',
 `active` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'user''s activation status',
 `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'user''s deletion status',
 `account_type` tinyint(1) NOT NULL DEFAULT '1' COMMENT 'user''s account type (basic, premium, etc)',
 `has_avatar` tinyint(1) NOT NULL DEFAULT '0' COMMENT '1 if user has a local avatar, 0 if not',
 `remember_me_token` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'user''s remember-me cookie token',
 `created_at` bigint(20) DEFAULT NULL COMMENT 'timestamp of the creation of user''s account',
 `suspened_at` bigint(20) DEFAULT NULL COMMENT 'Timestamp till the end of a user suspension',
 `last_login` bigint(20) DEFAULT NULL COMMENT 'timestamp of user''s last login',
 `failed_logins` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'user''s failed login attempts',
 `last_failed_login` int(10) DEFAULT NULL COMMENT 'unix timestamp of last failed login attempt',
 `activation_hash` varchar(80) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'user''s email verification hash string',
 `password_reset_hash` char(80) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'user''s password reset code',
 `password_reset_time` bigint(20) DEFAULT NULL COMMENT 'timestamp of the password reset request',
 `provider_type` text COLLATE utf8_unicode_ci,
 PRIMARY KEY (`ID`),
 UNIQUE KEY `name` (`name`),
 UNIQUE KEY `mail` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='user data';